project_id = "angsqeuyhyyxsqhfumtx"

[functions.calculate-chart]
verify_jwt = false

[functions.get-bodygraph]
verify_jwt = false

[functions.ipaymu-checkout]
verify_jwt = false

[functions.ipaymu-webhook]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false
